#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: "Dan's Pile"
title: "Dan's Pile"

# Short bio or description (displayed in the header)
description: "Some stuff I've found"

timezone: America/Chicago

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/254662

# Header image
header-img: https://i.imgur.com/QHgXB0P.jpg

# Pagination
paginate: 10
paginate_path: "/page/:num/"

#
# Flags below are optional
#

twitter:
  username: goodevilgenius
twitter_username: goodevilgenius

# Includes an icon in the footer for each username you enter
author:
  name: Dan Jones
  from: Texas, USA
  dribbble:
  email: 
  facebook: danjones
  flickr: goodevilgenius
  github: goodevilgenius
  instagram: goodevilgenius
  linkedin: danjones000
  pinterest:
  rss: https://pile.goodevilgenius.org/feed.xml # just type anything here for a working RSS icon
  twitter: goodevilgenius
  stackoverflow: users/367461/dan-jones # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: +DanJones000 # anything in your profile username that comes after plus.google.com/

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: danspile

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-51905064-3
# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-51905064-3

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://pile.goodevilgenius.org

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:year/:month/:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Makefile
  - less
  - Gruntfile.js
  - node_modules
  - package.json

#   # Site settings
# email: your-email@yourdomain.com
copyright_name: Dan Jones
github_username:  goodevilgenius
# facebook_username:  StartBootstrap
# email_username:  your-email@yourdomain.com


# # Build settings
# markdown: kramdown
# highlighter: rouge
# permalink: pretty
# paginate: 5
# exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# gems: [jekyll-paginate, jekyll-feed]

page_links:
  - title: About
    url: /about/
  - title: Archives
    url: /archives/
